[package]
name = "tf_rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.98"
env_logger = "0.11.8"
libc = "0.2.174"
log = "0.4.27"
once_cell = "1.21.3"
